const express=require('express'),session=require('express-session'),bcrypt=require('bcryptjs'),mysql=require('mysql2/promise'),path=require('path');
const app=express(),u=process.env.DATABASE_URL?new URL(process.env.DATABASE_URL):null;
const pool=mysql.createPool(u?{host:u.hostname,port:+(u.port||3306),user:decodeURIComponent(u.username),password:decodeURIComponent(u.password),database:u.pathname.slice(1),connectionLimit:10}:{host:process.env.MYSQLHOST||'127.0.0.1',port:+(process.env.MYSQLPORT||3306),user:process.env.MYSQLUSER||'root',password:process.env.MYSQLPASSWORD||'',database:process.env.MYSQLDATABASE||'rentops',connectionLimit:10});
app.use(express.json());app.use(session({secret:process.env.SESSION_SECRET||'change-me',resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:28800000}}));
async function init(){await pool.query(`CREATE TABLE IF NOT EXISTS users(id INT AUTO_INCREMENT PRIMARY KEY,username VARCHAR(100) UNIQUE NOT NULL,password_hash VARCHAR(255) NOT NULL);CREATE TABLE IF NOT EXISTS products(id INT AUTO_INCREMENT PRIMARY KEY,category ENUM('카메라','렌즈','액세서리') NOT NULL,name VARCHAR(255) NOT NULL,serial_number VARCHAR(255) UNIQUE NOT NULL,storage_location VARCHAR(255) NOT NULL,status ENUM('준비 중','대여 중','수리 중','점검 중') NOT NULL,component_notes TEXT);CREATE TABLE IF NOT EXISTS customers(id INT AUTO_INCREMENT PRIMARY KEY,company VARCHAR(255) NOT NULL,name VARCHAR(255) NOT NULL,phone VARCHAR(100) NOT NULL);CREATE TABLE IF NOT EXISTS rentals(id INT AUTO_INCREMENT PRIMARY KEY,customer_id INT NOT NULL,rental_date DATE NOT NULL,due_date DATE NOT NULL,rental_memo TEXT,returned_at DATE,return_memo TEXT,return_status ENUM('준비 중','점검 중','수리 중'),FOREIGN KEY(customer_id) REFERENCES customers(id));CREATE TABLE IF NOT EXISTS rental_items(id INT AUTO_INCREMENT PRIMARY KEY,rental_id INT NOT NULL,product_id INT NOT NULL,components_at_rental TEXT,missing_components TEXT,damage TEXT,UNIQUE KEY uq(rental_id,product_id),FOREIGN KEY(rental_id) REFERENCES rentals(id),FOREIGN KEY(product_id) REFERENCES products(id))`);
const [us]=await pool.query('SELECT id FROM users LIMIT 1');if(!us.length)await pool.query('INSERT INTO users(username,password_hash) VALUES(?,?)',['admin',bcrypt.hashSync(process.env.ADMIN_PASSWORD||'admin1234',12)]);
const [[n]]=await pool.query('SELECT COUNT(*) n FROM products');if(!+n.n){for(const x of [['카메라','Sony A7 IV','SNY-A7IV-001','A-01','준비 중'],['카메라','Sony A7S III','SNY-A7S3-014','A-02','준비 중'],['렌즈','FE 24-70mm F2.8 GM II','SNY-2470-022','L-03','점검 중'],['액세서리','DJI RS 4','DJI-RS4-008','ACC-02','수리 중'],['카메라','Canon R5','CAN-R5-031','A-07','준비 중'],['렌즈','RF 70-200mm F2.8 L IS','CAN-70200-017','L-08','준비 중']])await pool.query('INSERT INTO products(category,name,serial_number,storage_location,status) VALUES(?,?,?,?,?)',x);for(const x of [['ABC 프로덕션','홍길동','010-1234-5678'],['스튜디오 라이트','김민지','010-2456-7812']])await pool.query('INSERT INTO customers(company,name,phone) VALUES(?,?,?)',x)}}
const auth=(q,s,n)=>q.session.user?n():s.status(401).json({error:'로그인이 필요합니다.'});
app.post('/api/login',async(q,s)=>{const [a]=await pool.query('SELECT * FROM users WHERE username=?',[q.body.username||'']);const x=a[0];if(!x||!bcrypt.compareSync(q.body.password||'',x.password_hash))return s.status(401).json({error:'로그인 정보가 올바르지 않습니다.'});q.session.user={id:x.id,username:x.username};s.json(q.session.user)});
app.post('/api/logout',(q,s)=>q.session.destroy(()=>s.json({ok:true})));app.get('/api/me',(q,s)=>s.json(q.session.user||null));
app.get('/api/dashboard',auth,async(q,s)=>{const [[c],[t],[o]]=await Promise.all([pool.query('SELECT status,COUNT(*) n FROM products GROUP BY status'),pool.query('SELECT COUNT(*) n FROM products'),pool.query("SELECT r.id,c.company,c.name,r.due_date,GROUP_CONCAT(p.name SEPARATOR ', ') products,DATEDIFF(CURDATE(),r.due_date) delay_days FROM rentals r JOIN customers c ON c.id=r.customer_id JOIN rental_items i ON i.rental_id=r.id JOIN products p ON p.id=i.product_id WHERE r.returned_at IS NULL AND r.due_date<CURDATE() GROUP BY r.id ORDER BY r.due_date")]);s.json({total:t[0].n,counts:Object.fromEntries(c.map(x=>[x.status,x.n])),overdue:o})});
app.get('/api/products',auth,async(q,s)=>{let {q:x='',category='',status='',location=''}=q.query,sql='SELECT * FROM products WHERE 1=1',p=[];if(x){sql+=' AND(name LIKE ? OR serial_number LIKE ?)';p.push('%'+x+'%','%'+x+'%')}if(category){sql+=' AND category=?';p.push(category)}if(status){sql+=' AND status=?';p.push(status)}if(location){sql+=' AND storage_location LIKE ?';p.push('%'+location+'%')}const [a]=await pool.query(sql+' ORDER BY id DESC',p);s.json(a)});
app.post('/api/products',auth,async(q,s)=>{try{const b=q.body;const [r]=await pool.query('INSERT INTO products(category,name,serial_number,storage_location,status,component_notes) VALUES(?,?,?,?,?,?)',[b.category,b.name,b.serial_number,b.storage_location,b.status||'준비 중',b.component_notes||'']);s.json({id:r.insertId})}catch(e){s.status(400).json({error:e.code==='ER_DUP_ENTRY'?'S/N이 이미 등록되어 있습니다.':'제품 정보를 확인하세요.'})}});
app.get('/api/customers',auth,async(q,s)=>{const x='%'+(q.query.q||'')+'%';const [a]=await pool.query('SELECT c.*,SUM(CASE WHEN r.returned_at IS NULL THEN 1 ELSE 0 END) current_rentals FROM customers c LEFT JOIN rentals r ON r.customer_id=c.id WHERE c.company LIKE ? OR c.name LIKE ? OR c.phone LIKE ? GROUP BY c.id ORDER BY c.id DESC',[x,x,x]);s.json(a)});app.post('/api/customers',auth,async(q,s)=>{const [r]=await pool.query('INSERT INTO customers(company,name,phone) VALUES(?,?,?)',[q.body.company,q.body.name,q.body.phone]);s.json({id:r.insertId})});
app.get('/api/rentals',auth,async(q,s)=>{const [a]=await pool.query("SELECT r.*,c.company,c.name,GROUP_CONCAT(p.name SEPARATOR ', ') products FROM rentals r JOIN customers c ON c.id=r.customer_id JOIN rental_items i ON i.rental_id=r.id JOIN products p ON p.id=i.product_id GROUP BY r.id ORDER BY r.id DESC");const today=new Date().toISOString().slice(0,10);s.json(a.map(r=>({...r,derivedStatus:r.returned_at?'반납 완료':r.due_date<today?'반납 지연':r.due_date===today?'오늘 반납':'대여 중'})))});
async function tx(fn){const c=await pool.getConnection();try{await c.beginTransaction();const x=await fn(c);await c.commit();return x}catch(e){await c.rollback();throw e}finally{c.release()}}
app.post('/api/rentals',auth,async(q,s)=>{try{const id=await tx(async c=>{const ids=[...new Set(q.body.product_ids||[])];if(!ids.length)throw Error('제품을 선택하세요.');const [ps]=await c.query(`SELECT id,status FROM products WHERE id IN (${ids.map(()=>'?').join(',')}) FOR UPDATE`,ids);if(ps.length!==ids.length||ps.some(x=>x.status!=='준비 중'))throw Error('준비 중 상태인 장비만 대여할 수 있습니다.');const [r]=await c.query('INSERT INTO rentals(customer_id,rental_date,due_date,rental_memo) VALUES(?,?,?,?)',[q.body.customer_id,q.body.rental_date,q.body.due_date,q.body.rental_memo||'']);for(const id of ids){await c.query('INSERT INTO rental_items(rental_id,product_id,components_at_rental) VALUES(?,?,?)',[r.insertId,id,q.body.components_at_rental||'']);await c.query("UPDATE products SET status='대여 중' WHERE id=?",[id])}return r.insertId});s.json({id})}catch(e){s.status(400).json({error:e.message})}});
app.post('/api/rentals/return',auth,async(q,s)=>{try{await tx(async c=>{const [r]=await c.query('SELECT returned_at FROM rentals WHERE id=? FOR UPDATE',[q.body.rental_id]);if(!r.length||r[0].returned_at)throw Error('이미 반납 처리된 대여입니다.');await c.query('UPDATE rentals SET returned_at=?,return_status=?,return_memo=? WHERE id=?',[q.body.actual_return_date,q.body.return_status||'준비 중',q.body.return_memo||'',q.body.rental_id]);await c.query('UPDATE rental_items SET missing_components=?,damage=? WHERE rental_id=?',[q.body.missing_components||'',q.body.damage||'',q.body.rental_id]);const [it]=await c.query('SELECT product_id FROM rental_items WHERE rental_id=?',[q.body.rental_id]);for(const x of it)await c.query('UPDATE products SET status=? WHERE id=?',[q.body.return_status||'준비 중',x.product_id])});s.json({ok:true})}catch(e){s.status(400).json({error:e.message})}});
app.get('/health',async(q,s)=>{try{await pool.query('SELECT 1');s.json({ok:true})}catch(e){s.status(503).json({ok:false})}});app.use(express.static(path.join(__dirname,'public')));app.get('*',(q,s)=>s.sendFile(path.join(__dirname,'public/index.html')));init().then(()=>app.listen(process.env.PORT||3000)).catch(e=>{console.error(e);process.exit(1)});